/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mapeamento;

import ENUNS.DirecoesDoVento;
import ENUNS.SimOuNao;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *  SISTOM-4
 * @author Gustavo 
 * @creationDate 10/04/2016
 */
public class PainelDeSimulacao extends javax.swing.JPanel {

    private final String talhao;
    private final int umidade;
    private final int temperaturaMedia;
    private final int quantidadeInteracao;
    //SISTOM-9
    private final DirecoesDoVento direcao;
    private final SimOuNao chuva;
    private final Date data;
    private final int mediaHistorica;
    private static final SimpleDateFormat FORMATO_BR = new SimpleDateFormat("dd/MM/yyyy");

    /**
     *
     * @param frame
     * @param talhao
     * @param umid
     * @param temp
     * @param direcao
     * @param chuva
     * @param data
     * @param mediaHistorica
     * @param qtdInter
     */
    public PainelDeSimulacao(Abertura frame, String talhao, int umid, int temp, DirecoesDoVento direcao, SimOuNao chuva, Date data, int mediaHistorica, int qtdInter)
    {
        this.talhao = talhao;
        this.umidade = umid;
        this.temperaturaMedia = temp;
        this.quantidadeInteracao = qtdInter;    
        this.direcao = direcao;
        this.chuva = chuva;
        this.data = data;
        this.mediaHistorica = mediaHistorica;
        initComponents();
        mostrarVariaveisIniciais();
        MapaParaSimulacao mapaParaSimulacao = new MapaParaSimulacao(talhao);
        mapaParaSimulacao.setMinimumSize(new Dimension(400, 300));   
        painelMapa.add(mapaParaSimulacao, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        textPanel_interacaoAtual = new javax.swing.JTextPane();
        textPaneI_separador = new javax.swing.JTextPane();
        textPaneI_interacaoMaxima = new javax.swing.JTextPane();
        buttonIniciar = new javax.swing.JButton();
        buttonAnterior = new javax.swing.JButton();
        buttonProximo = new javax.swing.JButton();
        buttonMudar = new javax.swing.JButton();
        textPaneParametros = new javax.swing.JTextPane();
        painelMapa = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(400, 300));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        textPanel_interacaoAtual.setEditable(false);
        textPanel_interacaoAtual.setText("-");
        jPanel1.add(textPanel_interacaoAtual, new java.awt.GridBagConstraints());

        textPaneI_separador.setEditable(false);
        textPaneI_separador.setText("-");
        jPanel1.add(textPaneI_separador, new java.awt.GridBagConstraints());

        textPaneI_interacaoMaxima.setEditable(false);
        textPaneI_interacaoMaxima.setText("-");
        jPanel1.add(textPaneI_interacaoMaxima, new java.awt.GridBagConstraints());

        buttonIniciar.setText("Iniciar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 1);
        jPanel1.add(buttonIniciar, gridBagConstraints);

        buttonAnterior.setText("Anterior");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 1);
        jPanel1.add(buttonAnterior, gridBagConstraints);

        buttonProximo.setText("Proximo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 1);
        jPanel1.add(buttonProximo, gridBagConstraints);

        buttonMudar.setText("Mudar Parâmetros");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 1);
        jPanel1.add(buttonMudar, gridBagConstraints);

        textPaneParametros.setEditable(false);
        textPaneParametros.setText("...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 1);
        jPanel1.add(textPaneParametros, gridBagConstraints);
        textPaneParametros.getAccessibleContext().setAccessibleParent(jPanel1);

        painelMapa.setPreferredSize(new java.awt.Dimension(633, 364));
        painelMapa.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelMapa, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelMapa, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAnterior;
    private javax.swing.JButton buttonIniciar;
    private javax.swing.JButton buttonMudar;
    private javax.swing.JButton buttonProximo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel painelMapa;
    private javax.swing.JTextPane textPaneI_interacaoMaxima;
    private javax.swing.JTextPane textPaneI_separador;
    private javax.swing.JTextPane textPaneParametros;
    private javax.swing.JTextPane textPanel_interacaoAtual;
    // End of variables declaration//GEN-END:variables

    private void mostrarVariaveisIniciais() {
        textPanel_interacaoAtual.setText("1");
        textPaneI_interacaoMaxima.setText(Integer.toString(quantidadeInteracao));
        
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append("Umid.: ");
        stringBuilder.append(umidade);
        stringBuilder.append(",");
        stringBuilder.append(" Temp.: ");
         stringBuilder.append(temperaturaMedia);
          stringBuilder.append(",");
         stringBuilder.append(" Chuv.: ");
         stringBuilder.append(chuva.getValor()? "Sim" : "Não");
          stringBuilder.append(",");
          stringBuilder.append(" Direç.: ");
         stringBuilder.append(direcao.getValor());
          stringBuilder.append(",");
          stringBuilder.append(" Data.: ");
         stringBuilder.append(FORMATO_BR.format(data));
          stringBuilder.append(",");
          stringBuilder.append(" Média Hist.: ");
         stringBuilder.append(mediaHistorica);
        final String string = stringBuilder.toString();
        
        textPaneParametros.setText(string);
    }
}
