/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mapeamento;

import java.awt.BorderLayout;
import java.awt.Dimension;

/**
 *  SISTOM-4
 * @author Gustavo 
 * @creationDate 10/04/2016
 */
public class PainelDeSimulacao extends javax.swing.JPanel {

    private String talhao;
    /**
     * Creates new form PainelDeSimulacao
     * @param frame
     * @param talhao
     */
    public PainelDeSimulacao(Abertura frame,String talhao) {
        this.talhao = talhao;
        initComponents();
        Mapa button = new Mapa(talhao);
        button.setMinimumSize(new Dimension(400, 300));   
        painelMapa.add(button, BorderLayout.CENTER);
       
       
       
       
       // painelMapa.add(new JButton("teste"));
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        textPaneIteracoes = new javax.swing.JTextPane();
        buttonIniciar = new javax.swing.JButton();
        buttonAnterior = new javax.swing.JButton();
        buttonProximo = new javax.swing.JButton();
        buttonMudar = new javax.swing.JButton();
        textPaneParametros = new javax.swing.JTextPane();
        painelMapa = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(400, 300));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        textPaneIteracoes.setEditable(false);
        textPaneIteracoes.setText("0 - 15");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 1);
        jPanel1.add(textPaneIteracoes, gridBagConstraints);

        buttonIniciar.setText("Iniciar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 1);
        jPanel1.add(buttonIniciar, gridBagConstraints);

        buttonAnterior.setText("Anterior");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 1);
        jPanel1.add(buttonAnterior, gridBagConstraints);

        buttonProximo.setText("Proximo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 1);
        jPanel1.add(buttonProximo, gridBagConstraints);

        buttonMudar.setText("Mudar Parâmetros");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 1);
        jPanel1.add(buttonMudar, gridBagConstraints);

        textPaneParametros.setEditable(false);
        textPaneParametros.setText(" teste teste teste teste teste teste");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 1);
        jPanel1.add(textPaneParametros, gridBagConstraints);
        textPaneParametros.getAccessibleContext().setAccessibleParent(jPanel1);

        painelMapa.setPreferredSize(new java.awt.Dimension(633, 364));
        painelMapa.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAnterior;
    private javax.swing.JButton buttonIniciar;
    private javax.swing.JButton buttonMudar;
    private javax.swing.JButton buttonProximo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel painelMapa;
    private javax.swing.JTextPane textPaneIteracoes;
    private javax.swing.JTextPane textPaneParametros;
    // End of variables declaration//GEN-END:variables
}
